"""
Django settings for moodring project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import environ

environ.Env()
environ.Env.read_env()

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vod7rk+@)06^sxr^hrqv!n=!klqss@6n69ckbsmpb%jvg-o@jr"


DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "main_app",
    # REMOVE ALL OF THESE if you want a truly anonymous app without Admin
    # "django.contrib.admin",
    # "django.contrib.auth", # This was already gone, keep it gone
    # "django.contrib.contenttypes",
    # "django.contrib.sessions",
    # "django.contrib.messages",
    "django.contrib.staticfiles", # Keep this if you use static files (CSS/JS)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # REMOVE THESE as they are often tied to authentication/sessions/messages
    # "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "moodring.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
              "context_processors": [
                "django.template.context_processors.request",
                # REMOVE THIS if you removed django.contrib.messages
                # "django.contrib.messages.context_processors.messages",
                # Also ensure 'django.contrib.auth.context_processors.auth' is NOT here (it probably isn't by default if auth is removed)
            ],
        },
    },
]

WSGI_APPLICATION = "moodring.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mood",
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PW"],
        "HOST": os.environ["DB_HOST"],
        "PORT": "5432",
    }
}


# Password validation - REMOVE THIS ENTIRE SECTION if you don't have users
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# You should delete or comment out this entire block if no authentication is used.
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


import django_on_heroku

django_on_heroku.settings(locals(), databases=False)