# Generated by Django 5.2.3 on 2025-07-23 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😊'), ('Sad', 'Sad 😢'), ('Angry', 'Angry 😠'), ('Anxious', 'Anxious 😰'), ('Calm', 'Calm 😌'), ('Excited', 'Excited 🤩'), ('Tired', 'Tired 😴'), ('Grateful', 'Grateful 🙏'), ('Other', 'Other ✍️')], max_length=100)),
                ('intensity', models.CharField(choices=[('1', 'Subtle'), ('2', 'Mild'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Intense')], max_length=100)),
                ('journal_text', models.TextField(max_length=250)),
                ('affirmation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Journal Date')),
            ],
        ),
    ]
